name = "wp"
main = "src/index.ts"
compatibility_date = "2025-04-09"

[observability]
enabled = true

[vars]
API_HOST = "${API_HOST}"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "KV_BINDING"
id = "${KV_ID}"

[triggers]
crons = ["* * * * *"]
